# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version=0.3.7
maven_group=io.github.tr100000
archives_base_name=codec2schema

# Dependencies
# https://fabricmc.net/develop/
minecraft_version=26.3-pre-1
loom_version=1.17-SNAPSHOT
loader_version=0.19.5
fabric_version=0.159.1+26.3
trutils_version=0.3.0+26.2

# Publishing
modrinth_extra_minecraft_versions=
